{% set version = "0.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-distances
  version: {{ version|replace("-", "_") }}

source:
  fn: distances_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/distances_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/distances/distances_{{ version }}.tar.gz
  sha256: af039783067fbaa25359be10bccce427155e7fc4a10052b2eb91ad802e9d41d8

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('distances')"           # [not win]
    - "\"%R%\" -e \"library('distances')\""  # [win]

about:
  home: https://github.com/fsavje/distances
  license: GPL (>= 3)
  summary: Provides tools for constructing, manipulating and using distance metrics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - apcamargo
