{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-distances
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/distances_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/distances/distances_{{ version }}.tar.gz
  sha256: 8d2a9e01591d265e6a4de830d49e80255270cc34bed6bcac346d94535c3d1bf6

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('distances')"           # [not win]
    - "\"%R%\" -e \"library('distances')\""  # [win]

about:
  home: https://github.com/fsavje/distances
  license: GPL (>= 3)
  summary: Provides tools for constructing, manipulating and using distance metrics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Package: distances
# Type: Package
# Title: Tools for Distance Metrics
# Version: 0.1.6
# Date: 2018-12-12
# Authors@R: c(person("Fredrik", "Savje", email = "fredrik.savje@yale.edu", role = c("aut", "cre")))
# Description: Provides tools for constructing, manipulating and using distance metrics.
# Depends: R (>= 3.4.0)
# Imports: stats
# Suggests: testthat
# NeedsCompilation: yes
# License: GPL (>= 3)
# LicenseNote: The distances packages includes the ANN library (distributed under the LGPLv2.1 license).
# URL: https://github.com/fsavje/distances
# BugReports: https://github.com/fsavje/distances/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Packaged: 2018-12-12 21:08:19 UTC; fredriksavje
# Author: Fredrik Savje [aut, cre]
# Maintainer: Fredrik Savje <fredrik.savje@yale.edu>
# Repository: CRAN
# Date/Publication: 2018-12-12 23:00:03 UTC
