appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qkB914XecPc7FVs9yF+49xPpP0pValiIJmzagDWppRvYlIN5ql7plV+8qMBN8LdxMfF6z2O4OrTHBuC6eRDEMoUqs7fXF651gmV3/kbN/P6f5fuzh5czRvDi2G6NdoaDkBraLHYQFs6jMxK5W848DR1rnalvEGr0/m8URsDEOioIEDbyklT4zD+pc1Ja8zBBYnDQpNvjaAVNaClyE4jjb5An8rXKGnpvvrCkmgsxCX2J4F/oJxzFWyOEDWc1WaTERpXVwABIUYUVVOdCUNenOGWUao6k7I7WFaOQpp61JDoqLw4OzRiDaer68h2EgDLqKfxfQS3DhwZauUjoClc/r2RHl+pnRafj1dx/klp1Y2MtKSzi1FXjOjXWOqv4ta21Ce2QYfkMiwSpVZ7Us4e2Fj18JVqOHfHF9XGPHdWSP/g0UG9CNh+vClMyNaR0nT+e4yytJQ5UAFZLJo7r3oD7D16Ns01KAZlAbjOh9z9PaF6BJow/SzwJmmLtPuyLUUW/4PdiKIPCBZ1m+3eTEnu84kAT1K0wUlpa7KvB7YBk0Rm0NHVO+WD3S5kkCmfBmeuaQZyCVwcEnH1rq+iJixIzA/RG0gCxsAK38EzCLipNHMPVJFeF+h/SbheiKTOmJ2h0YLPjyN8TAo+O8IV8AA5rsMKhu9Vj5cZ6ela13Gl6jLw=}
